platform :ios, '14.0'
inhibit_all_warnings!
install! 'cocoapods', :disable_input_output_paths => true

target 'WYJSDKDemo' do
  use_frameworks!
  pod 'WYJKit', :path => 'DevPods/WYJKit/WYJKit.podspec', :modular_headers => true
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  
  # 赋予 .sh 脚本执行权限
  Dir.glob("Pods/Target Support Files/**/*.sh") do |file|
    FileUtils.chmod("+x", file)
  end
end
