# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods', :disable_input_output_paths => true
target 'WYJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WYJSDKDemo

  
  pod 'WYJKit', :path => 'DevPods/WYJKit/WYJKit.podspec'
  
end
