# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!
install! 'cocoapods', :disable_input_output_paths => true
target 'WYJSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WYJSDKDemo

  
  pod 'WYJKit', :path => 'DevPods/WYJKit/WYJKit.podspec'
  
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
