# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WYJKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'IQKeyboardManager'
pod 'DZNEmptyDataSet'
pod 'MJRefresh'
pod 'Masonry'
#pod 'YYKit'
pod 'FLEX','4.6.0', :configurations => ['Debug']#调试神器(模拟器按s,会出现视图层级关系)
pod 'QMUIKit' #功能说明 https://qmuiteam.com/ios/documents/
  target 'WYJKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WYJKitDemoUITests' do
    # Pods for testing
  end

end
