# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WYJKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'DZNEmptyDataSet'
  pod 'FLEX'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'ReactiveObjC'
  pod 'IQKeyboardManager'
end
