# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'WYJKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'DZNEmptyDataSet'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
end
