# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'YJKitDemo' do
  use_frameworks!
  pod 'MJRefresh'
  pod 'DZNEmptyDataSet'
#  pod 'WYJKits'
  pod 'Masonry'
  pod 'IQKeyboardManager'
end
